### PR TITLE
Removing "AtF Spark" - website offline

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @brabadu 

just removing a dead link from the list!

Cheers!

### CODE REVIEW

**Comment by brabadu** [comment]
Wow, thanks for pointing out! Repo for this font still exists though https://github.com/aftertheflood/sparks

I'll change a link to github repo

**Comment by brabadu** [comment]
Or you can do it in this PR, if you'd like

**Comment by spekulatius** [comment]
Ah cool. I'll update my PR - one second.

**Comment by spekulatius** [comment]
Done @brabadu

**Comment by brabadu** [comment]
Awesome! Thanks, @spekulatius !

**Comment by spekulatius** [comment]
Thanks for merging @brabadu !

**Pull request merged**
